//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eutyches.Spell.Lexedit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eutyches.Spell.Lexedit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aff.
        /// </summary>
        internal static string AffixFileExtension {
            get {
                return ResourceManager.GetString("AffixFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunspell Affix File (*.aff)|*.aff|All Files (*.*)|*.*.
        /// </summary>
        internal static string AffixFileFilter {
            get {
                return ResourceManager.GetString("AffixFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lexedit.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save lexicon.
        /// </summary>
        internal static string CloseLexiconFileDialogAffirmative {
            get {
                return ResourceManager.GetString("CloseLexiconFileDialogAffirmative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes have not been saved..
        /// </summary>
        internal static string CloseLexiconFileDialogExtra {
            get {
                return ResourceManager.GetString("CloseLexiconFileDialogExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close anyway.
        /// </summary>
        internal static string CloseLexiconFileDialogNegative {
            get {
                return ResourceManager.GetString("CloseLexiconFileDialogNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the lexicon?.
        /// </summary>
        internal static string CloseLexiconFileDialogQuestion {
            get {
                return ResourceManager.GetString("CloseLexiconFileDialogQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Lexicon File.
        /// </summary>
        internal static string CloseLexiconFileDialogTitle {
            get {
                return ResourceManager.GetString("CloseLexiconFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dic.
        /// </summary>
        internal static string DictionaryFileExtension {
            get {
                return ResourceManager.GetString("DictionaryFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hunspell Dictionary File (*.dic)|*.aff|All Files (*.*)|*.*.
        /// </summary>
        internal static string DictionaryFileFilter {
            get {
                return ResourceManager.GetString("DictionaryFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during the operation: {0}..
        /// </summary>
        internal static string ErrorDialogMessageFormat {
            get {
                return ResourceManager.GetString("ErrorDialogMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        internal static string ErrorReferrer {
            get {
                return ResourceManager.GetString("ErrorReferrer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Duplicates found!.
        /// </summary>
        internal static string ErrorStemDuplicates {
            get {
                return ResourceManager.GetString("ErrorStemDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form cannot contain whitespace..
        /// </summary>
        internal static string ErrorStemFormContainsWhiteSpace {
            get {
                return ResourceManager.GetString("ErrorStemFormContainsWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form cannot be empty, whitespace or the default string (e.g., &quot;0&quot;)..
        /// </summary>
        internal static string ErrorStemFormEmpty {
            get {
                return ResourceManager.GetString("ErrorStemFormEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Stem not found!.
        /// </summary>
        internal static string ErrorStemNotFound {
            get {
                return ResourceManager.GetString("ErrorStemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception ocurred..
        /// </summary>
        internal static string ErrorUnhandledException {
            get {
                return ResourceManager.GetString("ErrorUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save lexicon.
        /// </summary>
        internal static string ExitAppDialogAffirmative {
            get {
                return ResourceManager.GetString("ExitAppDialogAffirmative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to the lexicon have not been saved..
        /// </summary>
        internal static string ExitAppDialogExtra {
            get {
                return ResourceManager.GetString("ExitAppDialogExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit anyway.
        /// </summary>
        internal static string ExitAppDialogNegative {
            get {
                return ResourceManager.GetString("ExitAppDialogNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the lexicon before exiting?.
        /// </summary>
        internal static string ExitAppDialogQuestion {
            get {
                return ResourceManager.GetString("ExitAppDialogQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitAppDialogTitle {
            get {
                return ResourceManager.GetString("ExitAppDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Hunspell Affix File.
        /// </summary>
        internal static string ExportAffixFileDialogTitle {
            get {
                return ResourceManager.GetString("ExportAffixFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Hunspell Dictionary File.
        /// </summary>
        internal static string ExportDictionaryFileDialogTitle {
            get {
                return ResourceManager.GetString("ExportDictionaryFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Stems.
        /// </summary>
        internal static string ExportStemsFileDialogTitle {
            get {
                return ResourceManager.GetString("ExportStemsFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Affixes.
        /// </summary>
        internal static string ImportAffixesFileDialogTitle {
            get {
                return ResourceManager.GetString("ImportAffixesFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImportErrors.tgx.
        /// </summary>
        internal static string ImportErrorsDefaultFileName {
            get {
                return ResourceManager.GetString("ImportErrorsDefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Stems.
        /// </summary>
        internal static string ImportStemsFileDialogTitle {
            get {
                return ResourceManager.GetString("ImportStemsFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImportWarnings.tgx.
        /// </summary>
        internal static string ImportWarningsDefaultFileName {
            get {
                return ResourceManager.GetString("ImportWarningsDefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lex.
        /// </summary>
        internal static string LexiconFileDefaultExtension {
            get {
                return ResourceManager.GetString("LexiconFileDefaultExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lexica (*.lex, *.zlex)|*.lex;*.zlex|All Files (*.*)|*.*.
        /// </summary>
        internal static string LexiconFileFilter {
            get {
                return ResourceManager.GetString("LexiconFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save item.
        /// </summary>
        internal static string MoveCurrentItemDialogAffirmative {
            get {
                return ResourceManager.GetString("MoveCurrentItemDialogAffirmative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo changes.
        /// </summary>
        internal static string MoveCurrentItemDialogNegative {
            get {
                return ResourceManager.GetString("MoveCurrentItemDialogNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to the current item have not been saved..
        /// </summary>
        internal static string MoveCurrentItemDialogOperation {
            get {
                return ResourceManager.GetString("MoveCurrentItemDialogOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes before moving to another item?.
        /// </summary>
        internal static string MoveCurrentItemDialogQuestion {
            get {
                return ResourceManager.GetString("MoveCurrentItemDialogQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Current Item.
        /// </summary>
        internal static string MoveCurrentItemDialogTitle {
            get {
                return ResourceManager.GetString("MoveCurrentItemDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [new lexicon].
        /// </summary>
        internal static string NewFileName {
            get {
                return ResourceManager.GetString("NewFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [new item].
        /// </summary>
        internal static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Lexicon File.
        /// </summary>
        internal static string OpenLexiconFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenLexiconFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Tagged Stem File.
        /// </summary>
        internal static string OpenTaggedStemFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenTaggedStemFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove stem.
        /// </summary>
        internal static string RemoveStemDialogAffirmative {
            get {
                return ResourceManager.GetString("RemoveStemDialogAffirmative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once the stem is removed, all affected stems will be updated and their references will be deleted. Remove it only if these relationships are no longer valid..
        /// </summary>
        internal static string RemoveStemDialogCaution {
            get {
                return ResourceManager.GetString("RemoveStemDialogCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This stem has derivatives. The following number of stems will be affected:.
        /// </summary>
        internal static string RemoveStemDialogExtraHasRelations {
            get {
                return ResourceManager.GetString("RemoveStemDialogExtraHasRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This stem has no derivatives. It might be OK to remove..
        /// </summary>
        internal static string RemoveStemDialogExtraNoRelations {
            get {
                return ResourceManager.GetString("RemoveStemDialogExtraNoRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not remove.
        /// </summary>
        internal static string RemoveStemDialogNegative {
            get {
                return ResourceManager.GetString("RemoveStemDialogNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this stem: {0} ({1})?.
        /// </summary>
        internal static string RemoveStemDialogQuestionFormat2 {
            get {
                return ResourceManager.GetString("RemoveStemDialogQuestionFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Referring as Root: {0}
        ///- Referring as Base: {1}.
        /// </summary>
        internal static string RemoveStemDialogRelationCountFormat {
            get {
                return ResourceManager.GetString("RemoveStemDialogRelationCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Stem.
        /// </summary>
        internal static string RemoveStemDialogTitle {
            get {
                return ResourceManager.GetString("RemoveStemDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Lexicon File.
        /// </summary>
        internal static string SaveLexiconFileDialogTitle {
            get {
                return ResourceManager.GetString("SaveLexiconFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed lexicon.
        /// </summary>
        internal static string StatusLexiconClosed {
            get {
                return ResourceManager.GetString("StatusLexiconClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New lexicon created.
        /// </summary>
        internal static string StatusLexiconCreated {
            get {
                return ResourceManager.GetString("StatusLexiconCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed lexicon {0}.
        /// </summary>
        internal static string StatusLexiconDataChangedFormat {
            get {
                return ResourceManager.GetString("StatusLexiconDataChangedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        internal static string StatusLexiconError {
            get {
                return ResourceManager.GetString("StatusLexiconError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened lexicon {0}.
        /// </summary>
        internal static string StatusLexiconOpenedFormat {
            get {
                return ResourceManager.GetString("StatusLexiconOpenedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved lexicon {0}.
        /// </summary>
        internal static string StatusLexiconSavedFormat {
            get {
                return ResourceManager.GetString("StatusLexiconSavedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        internal static string StemRelationsToolWindowBaseMode {
            get {
                return ResourceManager.GetString("StemRelationsToolWindowBaseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string StemRelationsToolWindowRootMode {
            get {
                return ResourceManager.GetString("StemRelationsToolWindowRootMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stem Associations.
        /// </summary>
        internal static string StemRelationsToolWindowTitle {
            get {
                return ResourceManager.GetString("StemRelationsToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tgx.
        /// </summary>
        internal static string TaggedStemFileDefaultExtension {
            get {
                return ResourceManager.GetString("TaggedStemFileDefaultExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagged Stems (*.tgx, *.txt)|*.tgx;*.txt|All Files (*.*)|*.*.
        /// </summary>
        internal static string TaggedStemFileFilter {
            get {
                return ResourceManager.GetString("TaggedStemFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningDialogTitle {
            get {
                return ResourceManager.GetString("WarningDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
    }
}
