//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eutyches.Spell.Hunspell.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eutyches.Spell.Hunspell.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjectival.
        /// </summary>
        public static string CategoryAdjectival {
            get {
                return ResourceManager.GetString("CategoryAdjectival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adpositional.
        /// </summary>
        public static string CategoryAdpositional {
            get {
                return ResourceManager.GetString("CategoryAdpositional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adverbial.
        /// </summary>
        public static string CategoryAdverbial {
            get {
                return ResourceManager.GetString("CategoryAdverbial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conjunctive.
        /// </summary>
        public static string CategoryConjunctive {
            get {
                return ResourceManager.GetString("CategoryConjunctive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determinative.
        /// </summary>
        public static string CategoryDeterminative {
            get {
                return ResourceManager.GetString("CategoryDeterminative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign.
        /// </summary>
        public static string CategoryForeign {
            get {
                return ResourceManager.GetString("CategoryForeign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional.
        /// </summary>
        public static string CategoryFunctional {
            get {
                return ResourceManager.GetString("CategoryFunctional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interjection.
        /// </summary>
        public static string CategoryInterjection {
            get {
                return ResourceManager.GetString("CategoryInterjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterrogative.
        /// </summary>
        public static string CategoryInterrogative {
            get {
                return ResourceManager.GetString("CategoryInterrogative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal.
        /// </summary>
        public static string CategoryNominal {
            get {
                return ResourceManager.GetString("CategoryNominal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric.
        /// </summary>
        public static string CategoryNumeric {
            get {
                return ResourceManager.GetString("CategoryNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string CategoryOther {
            get {
                return ResourceManager.GetString("CategoryOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronominal.
        /// </summary>
        public static string CategoryPronominal {
            get {
                return ResourceManager.GetString("CategoryPronominal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Categorized.
        /// </summary>
        public static string CategoryUncategorized {
            get {
                return ResourceManager.GetString("CategoryUncategorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbal.
        /// </summary>
        public static string CategoryVerbal {
            get {
                return ResourceManager.GetString("CategoryVerbal", resourceCulture);
            }
        }
    }
}
